### ISSUE TITLE
python3 libary lxml not installed

### ISSUE THREAD

**Issue by DO1JLR** [alvistack/ansible-role-fisheye#3]
Hi. Thanks for this role.

I found out that the pythoon libary lxml is required to be present at the remote host. But will not be installed with this ansible.

Is there a reason for it? Otherwise I would apreciate if we can add it to this role!

```yaml
TASK [fisheye : patch /opt/atlassian/fisheye/content/WEB-INF/web.xml] ***********************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'lxml'
fatal: [atlassian-fisheye.wingcon.com]: FAILED! => changed=false 
  msg: Failed to import the required Python library (lxml) on fisheye-test's Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter

```

**Comment by DO1JLR** [comment]
I see you say you have a additional role to install python stuff:
https://github.com/alvistack/ansible-role-fisheye/blob/master/ansible-galaxy-requirements.yml#L26L29

nevertheless, i think it would be nicer if such dependencies could be solved right here in the role. What do you think?

**Comment by hswong3i** [comment]
First we default everything with python 3 only, so you need to ensure target already have it.

Next we default with custom pip3 installation, in order to minimize OS package dependency issue (some could update but some can’t); again you need to ensure it before running this role.

Finally once above issues solved, now we could install the python lxml package; BTW it is an Ansible-specific requirement on python but not Fisheye’s requirement...

Therefore lxml should be handled by python role but not here. Please simply run ‘molecule converge’ and dependency will be download automatically ;-)
